name: Node.js CI

on:
  push:
    branches:
      - '*'

jobs:

  test-node:

#    runs-on: ubuntu-latest
    runs-on: macos-latest
    environment: test-ethers

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Install node-hid requirements
#        run: sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev libudev-dev

      - name: Install dependencies (and link per package)
        run: npm ci

      - name: Build CommonJS and ESM (from TypeScript)
        run: npm run build-all

      - name: Run tests
        run: npm run test-node

